apiVersion: v1
kind: Service
metadata:
  name: stablecoin-service
spec:
  selector:
    app: stablecoin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # External access
